version: '2'
services:
  pijuice:
    build: ./pijuice
    privileged: true
    network_mode: host
    labels: 
      io.balena.features.balena-api: '1'
      io.balena.features.kernel-modules: '1'
